### PR TITLE
fix(allow_spam_TLDs.txt): added some urls and removed non-working urls

### PR DESCRIPTION
**Pull request by olivertzeng**
including userstyles.world

### CODE REVIEW

**Comment by hagezi** [comment]
@olivertzeng Please do not remove any domains, the list is still used for other things, my build system automatically sorts out dead and unneeded domains. Please adjust the PR.

**Comment by olivertzeng** [comment]
@hagezi done

**Comment by hagezi** [comment]
@olivertzeng I have adapted my scripts and will only list the active domains used as exclusions in the spam TLDs.

**Comment by olivertzeng** [comment]
nice


使用 Proton Mail 安全電子郵件傳送。

在 2024年7月17日 星期三 13:13，Gerd ***@***.***> 寫道：

**Pull request merged**
