### PR TITLE
Update deny_light-ultimate.txt

### PR DESCRIPTION
**Pull request by vhpcdpgl**

### CODE REVIEW

**Comment by hagezi** [comment]
What kind of domains are these, more details please?

**Comment by vhpcdpgl** [comment]
`https://bgp.he.net/net/14.225.10.0/24#_dnsrecords`

**Comment by hagezi** [comment]
@vhpcdpgl Don't these belong in the PopupAds list?

The domains cannot be found on my merged top list of the last 14 months (Umbrella, Cloudflare, Tranco, DomCop ...) with around 30 million domains. They are probably never accessed. Are there any examples where they are used?

**Comment by vhpcdpgl** [comment]
Some of these domains [`https://bgp.he.net/net/123.30.151.0/24#_dnsrecords`] blocked: `philacct.com, sourcetobin.com, tebrand.asia, admicro.vn, deqik.com, modestsunf.com`
I think maybe they are popular on websites in Vietnam.

**Pull request closed without merging**
