### PR TITLE
Add Tagcommander CDN

### PR DESCRIPTION
**Pull request by xRuffKez**
HERE Map Location Tags

### CODE REVIEW

**Comment by hagezi** [comment]
@xRuffKez The domain was removed from the non-aggressive lists because the EDEKA store search does not work otherwise. It would have to be checked again.

**Comment by xRuffKez** [comment]
Yep but present on Pro++
Else it's my personallist then.

**Comment by hagezi** [comment]
Yes, it is still blocked in the aggressive lists. Not in light to pro.

**Comment by xRuffKez** [comment]
Will it remain blocked? Else i will close this PR

**Comment by hagezi** [comment]
I think there are also other restrictions if the domain is blocked. But I'll have to look that up first.

**Comment by hagezi** [comment]
The domain remains blocked in the Ultimate in any case. So this Allowlist is the wrong one. I'll check again, if there are more restrictions than EDEKA, then I'll unblock them in Pro++, otherwise not.

**Pull request closed without merging**
