### PR TITLE
Update deny_tif-ips.txt

### PR DESCRIPTION
**Pull request by vhpcdpgl**

### CODE REVIEW

**Comment by iam-py-test** [comment]
I am sorry, but it appears you may have accidentally added these entries into the wrong file. These are gambling websites, but they were added to the file for the threat intelligence feeds.
I apologize if I am mistaken.
Thanks

**Comment by vhpcdpgl** [comment]
> I am sorry, but it appears you may have accidentally added these entries into the wrong file. These are gambling websites, but they were added to the file for the threat intelligence feeds.
> I apologize if I am mistaken.
> Thanks

So how to block gambling IPs?

**Comment by iam-py-test** [comment]
I do not think there is a gambling IPs list, so hagezi would have to create one.
Thank you

**Comment by hagezi** [comment]
Yes, there is currently no IP list for gambling. Would that be worthwhile? Would you maintain the list @vhpcdpgl ?

**Comment by vhpcdpgl** [comment]
> Yes, there is currently no IP list for gambling. Would that be worthwhile? Would you maintain the list @vhpcdpgl ?

Maybe later ^_^

**Pull request closed without merging**
