### PR TITLE
Add Ongoing Phishing Domains

### PR DESCRIPTION
**Pull request by xRuffKez**
Extracted from various IPs i investigated, checked against 1M List of Cisco and bulk scanned them,

### CODE REVIEW

**Comment by hagezi** [comment]
@xRuffKez Have you checked the domains against the TIF?

Please make it available as an extra list first, I want to run it through the deadcheck first. In addition, the denylist is part of multi, which would exceed the list sizes of the normal lists.

Thank you,
Gerd

**Comment by xRuffKez** [comment]
Yep, that is why i closed it. Checking,,,

**Comment by hagezi** [comment]
@xRuffKez You can simply create a new file with `list_` suffix in the PR directory, e.g. `list_phishing.txt`

I then look at it and add it to the TIF as source. This list can then be updated.

**Comment by hagezi** [comment]
@xRuffKez Check against TIF:
```
curl -SL https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt | grep -Ev '^\s*$|^#|^!' > tif.txt
grep -F -wv -f tif.txt <PHISHING_LIST_FILENAME> >not_on_tif-txt
```

**Comment by xRuffKez** [comment]
> @xRuffKez You can simply create a new file with `list_` suffix in the PR directory, e.g. `list_phishing.txt`
> 
> I then look at it and add it to the TIF as source. This list can then be updated.

Sorry i PRed. Haven't read your comment before.

**Comment by hagezi** [comment]
@xRuffKez The two files must have unix/linux line endings for the grep, if your list does not have this, it must be converted with dos2unix.

**Comment by xRuffKez** [comment]
> @xRuffKez The two files must have unix/linux line endings for the grep, if your list does not have this, it must be converted with dos2unix.

I don't work on Windows. But i know what you mean. I did that with a py.
Thanks for the hint!

**Comment by hagezi** [comment]
@xRuffKez The grep is convenient because you simulate wildcard blocking with word-by-word comparison, because if example.com is on the TIF, *.example.com is removed from your list. A line-by-line comparison does not produce the desired result.

**Pull request closed without merging**
