### PR TITLE
Add DNS evading through DoT/DoH Domains

### PR DESCRIPTION
**Pull request by xRuffKez**
Added DoT/DoH Public Resolver Domains, which are widely used. Also contains Resolver Domains known in the Evasion List, but different sub domain versions.

### CODE REVIEW

**Comment by hagezi** [comment]
@xRuffKez Incidentally, they were all already on the doh-vpn-proxy-bypass list, except for non-resolving domains.

**Comment by xRuffKez** [comment]
Something went wrong on comparison.

**Comment by hagezi** [comment]
@xRuffKez I recreated the list with the updated denylist and saw that there are no changes from the previous version. I then randomly checked a few domains and they were already included.

One more note, DoH should be on the DoH denylist so that they also end up on the DoH only bypass list. The domains are then automatically transferred to the entire bypass list.

The bypass does not contain NXDOMAIN, SERFFAIL or domains that do not have an A record.

**Comment by xRuffKez** [comment]
I mixed the command up in grep 😆

**Comment by xRuffKez** [comment]
https://github.com/hagezi/dns-blocklists/pull/2329

**Pull request merged**
