### PR TITLE
Update allow_spam_TLDs.txt

### PR DESCRIPTION
**Pull request by olivertzeng**
added a lot of privacy instances

### CODE REVIEW

**Comment by hagezi** [comment]
Thanks for the support, but not every normal domain will be excluded/allowed. In principle, only popular domains that have been on relevant top lists (Umbrella, Cloudflare, Tranco, Chrome, DomCop, ...) in the last 12 months or disrupt the functionality of popular apps, websites or services are excluded.
If this requirement is not met, it will be decided on a case-by-case basis whether the domains will be excluded.
Allowing must be done in the personal allowlist.

The reason for this procedure is that the length of the denyallow/domain modifier in lists formatted for AdGuard or uBlock is limited before the rule becomes invalid. This means that if every normal domain of the corresponding TLD were to be excluded, important rules would become invalid at some point. It must therefore be carefully weighed up what is excluded and what is not.

Furthermore, adding subdomains to Denyallow makes no sense. Only SLDs should be excluded.

When I have time, I'll take a look at the domains.

This list here is not a general allowlist, it is only used to form the exclusions for the AdGuard and uBlock list.

**Comment by olivertzeng** [comment]
> Thanks for the support, but not every normal domain will be excluded/allowed. In principle, only popular domains that have been on relevant top lists (Umbrella, Cloudflare, Tranco, Chrome, DomCop, ...) in the last 12 months or disrupt the functionality of popular apps, websites or services are excluded. If this requirement is not met, it will be decided on a case-by-case basis whether the domains will be excluded. Allowing must be done in the personal allowlist.
> 
> The reason for this procedure is that the length of the denyallow/domain modifier in lists formatted for AdGuard or uBlock is limited before the rule becomes invalid. This means that if every normal domain of the corresponding TLD were to be excluded, important rules would become invalid at some point. It must therefore be carefully weighed up what is excluded and what is not.
> 
> Furthermore, adding subdomains to Denyallow makes no sense. Only SLDs should be excluded.
> 
> When I have time, I'll take a look at the domains.
> 
> This list here is not a general allowlist, it is only used to form the exclusions for the AdGuard and uBlock list.

i understand i will sort out unpopular stuff that even i dont use

**Comment by olivertzeng** [comment]
> Thanks for the support, but not every normal domain will be excluded/allowed. In principle, only popular domains that have been on relevant top lists (Umbrella, Cloudflare, Tranco, Chrome, DomCop, ...) in the last 12 months or disrupt the functionality of popular apps, websites or services are excluded. If this requirement is not met, it will be decided on a case-by-case basis whether the domains will be excluded. Allowing must be done in the personal allowlist.
> 
> The reason for this procedure is that the length of the denyallow/domain modifier in lists formatted for AdGuard or uBlock is limited before the rule becomes invalid. This means that if every normal domain of the corresponding TLD were to be excluded, important rules would become invalid at some point. It must therefore be carefully weighed up what is excluded and what is not.
> 
> Furthermore, adding subdomains to Denyallow makes no sense. Only SLDs should be excluded.
> 
> When I have time, I'll take a look at the domains.
> 
> This list here is not a general allowlist, it is only used to form the exclusions for the AdGuard and uBlock list.

well the links i've added have some 'categories'

1. nitter/lemmy/searx/others instances
2. popcat popdog these kind of cool sites
3. famous sites like www.bandainamcoent.asia

which do i remove?

**Comment by hagezi** [comment]
Leave the PR open, I'll have a look at it, I'm careful with instances, it's more for the personal allowlist, there are just too many.

I'll then adjust the PR.

**Comment by olivertzeng** [comment]
Alr good luck
 Sent from Proton Mail for iOS 
於 週二, 7月 23, 2024 時間 23:35, Gerd ***@***.***&gt; 寫道：  Leave the PR open, I'll have a look at it, I'm careful with instances, it's more for the personal allowlist, there are just too many.
I'll then adjust the PR.

**Pull request closed without merging**
