### PR TITLE
Fix a false positive for dns.yandex.ru

### PR DESCRIPTION
**Pull request by Yushkevichav**
Fixed a false positive for dns.yandex.ru

### CODE REVIEW

**Comment by hagezi** [comment]
Why should the domain be removed? Makes no sense to me.

**Comment by Yushkevichav** [comment]
Because dns.yandex.ru it is not a doh domain. This is just a link to the yandex dns page

**Comment by hagezi** [comment]
image

There are doh instances on the domain, so it remains blocked.

**Comment by Yushkevichav** [comment]
Yes, but exactly dns.yandex.ru is not a doh. Anyway, I couldn't use it as a doh. However, if you say that this is an instance, then I believe you

**Comment by hagezi** [comment]
I block the main domain to block all possible doh instances on subdomains. Important for blockers that support wildcard blocking. This saves having to add new subdomains.

**Pull request closed without merging**
